FROM rust:1.76

RUN apt-get update \
  && apt-get install -y clang git \
  && rustup component add rustfmt \
  && rustup component add clippy \
  && cargo install cargo-watch

RUN git clone https://github.com/rui314/mold.git \
  && mkdir /mold/build \
  && cd /mold/build \
  && git checkout v1.7.1 \
  && ../install-build-deps.sh \
  && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/c++ .. \
  && cmake --build . -j $(nproc) \
  && cmake --install .

WORKDIR /backend

CMD cargo watch -x "run --bin nimble-server"
