name: Build and Push Docker image

on:
  push:
    branches: [main, feature/gh-actions]

jobs:
  push_to_registry:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/southball/nimble
        tags: |
          type=sha
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v1
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: southball
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      if: github.event_name != 'pull_request'
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
